---
# Dieses Repo ist Teil des Heimgewebes.
# Systemweiter Kontext durch Heimgeist:
#   metarepo/ai-contexts/heimgeist.ai-context.yml

system_context:
  heimgeist: "../metarepo/ai-contexts/heimgeist.ai-context.yml"

ai_context_version: 1.1

project:
  name: hauski-audio
  summary: Audio capture, VAD/ASR pipeline, and event emission.
  role: audio_to_text_events
  primary_language: mixed
  visibility: internal

heimgewebe:
  axis:
    - Events
    - Motorik
  fleet:
    enabled: true
  wgx:
    profile_expected: true
    guard_smoke_expected: true

interfaces:
  consumes:
    - "mic/streams"
  produces:
    - "event.line"

contracts:
  schemas:
    - path: "contracts/*.schema.json"
      note: "Reference canonical schemas"

dependencies:
  internal:
    - name: contracts
      relationship: uses
      interface:
        - audio_events_schema
    - name: chronik
      relationship: uses
      interface:
        - event_https_ingest
  external:
    - name: ffmpeg
    - name: whisper.cpp
      note: optional

architecture:
  entrypoints:
    - cli/*
  key_paths:
    - path: pipeline/
      purpose: VAD + ASR + packaging
  data_flow:
    input: mic/streams
    processing: segment → transcribe → package
    output: JSONL events

boundaries:
  not_responsible_for:
    - "Playback"
    - "Storage of events"
  dangerous_assumptions:
    - "Assume repo is Fleet-enabled without checking .wgx/"

conventions:
  branching: "main, feature/*"
  commit_prefix: "hauski-audio"
  ci_platform: github_actions

documentation:
  runbook: docs/runbook.md

ai_guidance:
  do:
    - emit small, well-formed JSONL chunks
  dont:
    - buffer giant payloads before send
